### ISSUE TITLE
Aspect Model documentation fails for larger models

### ISSUE THREAD

**Issue by georgschmidtdumont** [OpenManufacturingPlatform/sds-sdk#5]
**Describe the bug**
When generating the HTML documentation for an Aspect Model which contains an element chain, consisting of Collection Characteristics with Entities as the data-type, with more than 9 elements the HTML documentation generation fails with the following exception.

```
Max calling depth of 20 was exceeded in macro 'entity' with Call Stack:property->characteristic->Set->Collection->characteristic->Entity->entity->property->characteristic->Set->Collection->characteristic->Entity->entity->property->characteristic->Set->Collection->characteristic->Entity at /docu/templates/asciidoc/entity-documentation-lib.vm[line 2, column 1]
Exception in macro #entity called at /docu/templates/asciidoc/characteristic-documentation-lib.vm[line 24, column 1]
Exception in macro #Entity called at /docu/templates/asciidoc/aspect-model-documentation.vm[line 1, column 1]
Exception in macro #characteristic called at /docu/templates/asciidoc/characteristic-documentation-lib.vm[line 72, column 1]
Exception in macro #Collection called at /docu/templates/asciidoc/characteristic-documentation-lib.vm[line 56, column 1]
Exception in macro #Set called at /docu/templates/asciidoc/aspect-model-documentation.vm[line 1, column 1]
Exception in macro #characteristic called at /docu/templates/asciidoc/property-documentation-lib.vm[line 39, column 1]
Exception in macro #property called at /docu/templates/asciidoc/entity-documentation-lib.vm[line 8, column 1]
Exception in macro #entity called at /docu/templates/asciidoc/characteristic-documentation-lib.vm[line 24, column 1]
Exception in macro #Entity called at /docu/templates/asciidoc/aspect-model-documentation.vm[line 1, column 1]
Exception in macro #characteristic called at /docu/templates/asciidoc/characteristic-documentation-lib.vm[line 72, column 1]
Exception in macro #Collection called at /docu/templates/asciidoc/characteristic-documentation-lib.vm[line 56, column 1]
Exception in macro #Set called at /docu/templates/asciidoc/aspect-model-documentation.vm[line 1, column 1]
Exception in macro #characteristic called at /docu/templates/asciidoc/property-documentation-lib.vm[line 39, column 1]
Exception in macro #property called at /docu/templates/asciidoc/entity-documentation-lib.vm[line 8, column 1]
Exception in macro #entity called at /docu/templates/asciidoc/characteristic-documentation-lib.vm[line 24, column 1]
Exception in macro #Entity called at /docu/templates/asciidoc/aspect-model-documentation.vm[line 1, column 1]
Exception in macro #characteristic called at /docu/templates/asciidoc/characteristic-documentation-lib.vm[line 72, column 1]
Exception in macro #Collection called at /docu/templates/asciidoc/characteristic-documentation-lib.vm[line 56, column 1]
Exception in macro #Set called at /docu/templates/asciidoc/aspect-model-documentation.vm[line 1, column 1]
Exception in macro #characteristic called at /docu/templates/asciidoc/property-documentation-lib.vm[line 39, column 1]
Exception in macro #property called at /docu/templates/asciidoc/aspect-model-documentation.vm[line 13, column 1]
Exception in thread "main" java.lang.reflect.InvocationTargetException
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:49)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:108)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:58)
        at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:88)
Caused by: org.apache.velocity.exception.MacroOverflowException: Max calling depth of 20 was exceeded in macro 'entity' with Call Stack:property->characteristic->Set->Collection->characteristic->Entity->entity->property->characteristic->Set->Collection->characteristic->Entity->entity->property->characteristic->Set->Collection->characteristic->Entity at /docu/templates/asciidoc/entity-documentation-lib.vm[line 2, column 1]
        at org.apache.velocity.runtime.directive.VelocimacroProxy.checkDepth(VelocimacroProxy.java:338)
...
```

**Comment by atextor** [comment]
Fixed by #23
